DROP TABLE AE_USERS;

CREATE TABLE AE_USERS(
	AEID NUMBER(10) PRIMARY KEY,
	EMAIL varchar2(255),
	PASSWORD varchar2(255),
	ADMINLVL NUMBER(1),
	STATUS NUMBER(2)
);
DROP SEQUENCE AE_user_seq;

CREATE SEQUENCE AE_user_seq
	START WITH 1
	INCREMENT BY 1;

DROP TABLE AE_USERINFO;

CREATE TABLE AE_USERINFO(
	INFOID NUMBER(10) PRIMARY KEY,
	NICKNAME varchar2(255),
	BIRTHDATE varchar2(255),
	REGION varchar2(255),
	PROFILEPIC varchar2(4000),
	USER_INFOID NUMBER(10)
);

CREATE SEQUENCE AE_userinfo_seq
	START WITH 1
	INCREMENT BY 1;

DROP TABLE AE_BLOCKED;

CREATE TABLE AE_BLOCKED(
	BLOCKID NUMBER(10) PRIMARY KEY,
	BLOCKEDUSERID NUMBER(10),
	AE_ID NUMBER(10)
);

CREATE SEQUENCE AE_block_seq
	START WITH 1
	INCREMENT BY 1;

DROP TABLE AE_CHANNELS;

CREATE TABLE AE_CHANNELS(
	CHANNELID NUMBER(10) PRIMARY KEY,
	CHANNELNAME varchar2(255),
	CHANNELTYPE NUMBER(1)
);

CREATE SEQUENCE AE_CHANNEL_seq
	START WITH 1
	INCREMENT BY 1;

DROP TABLE AE_COMMENTS;

CREATE TABLE AE_COMMENTS(
	COMMENTID NUMBER(10) PRIMARY KEY,
	CONTENT varchar2(4000),
	POSTDATE varchar2(255),
	USER_ID NUMBER(10),
	CHANNEL_ID NUMBER(10)
);

CREATE SEQUENCE AE_COMMENTS_seq
	START WITH 1
	INCREMENT BY 1;

DROP TABLE AE_ALLOWED;

CREATE TABLE AE_ALLOWED(
	ALLOWID NUMBER(10) PRIMARY KEY,
	BANSTATUS NUMBER(1),
	USER_AID NUMBER(10),
	CHANNEL_AID NUMBER(10)
);

CREATE SEQUENCE AE_ALLOWED_seq
	START WITH 1
	INCREMENT BY 1;